module.exports = {
  INITIAL_POST_LIMIT: 15,
  AUTHOR_POST_LIMIT: 15,
  MIN_PLAGIARIST_CASES_FOR_COMMENT: 4,
  MIN_PLAGIARIST_CASES_FOR_REPORT: 5,
  MAX_COMMENT_AGE: 259200000,
  MIN_COMMENT_LENGTH: 20,
  MAX_REMAINDER_AUTHORS: 15,
  SIMILARITY_THRESHOLD: .85,
  SIMILARITY_THRESHOLD_LOOSE: .6,
}
