module.exports = {
  INITIAL_POST_LIMIT: 15,
  AUTHOR_POST_LIMIT: 15,
  MIN_PLAGIARIST_CASES_FOR_COMMENT: 4,
  MIN_PLAGIARIST_CASES_FOR_REPORT: 5,
  MAX_COMMENT_AGE: 1209600000,
  MIN_COMMENT_LENGTH: 20,
  MAX_REMAINDER_AUTHORS: 15,
  MAX_REMAINDER: 10000,
  MAX_AUTHORS_TO_SEARCH: 1,
  SIMILARITY_THRESHOLD: .85,
  SIMILARITY_THRESHOLD_LOOSE: .6,
}
